name: Resultados ONCE

on:
  workflow_dispatch:
  schedule:
    - cron: '30 21 * * *'
      timezone: 'Europe/Madrid'

jobs:
  generar-resultados:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar proyecto
        uses: actions/checkout@v4

      - name: Preparar Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Generar resultados
        run: python generar_resultados.py

      - name: Guardar mensaje
        uses: actions/upload-artifact@v4
        with:
          name: resultados-once
          path: salida/mensaje.txt
          retention-days: 7