name: Enviar Resultados ONCE

on:
  schedule:
    - cron: '30 21 * * *'
  workflow_dispatch:

jobs:
  publicar:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repositorio
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependencias
        run: |
          pip install requests beautifulsoup4

      - name: 1. Generar resultados.json
        run: python generar_resultados.py

      - name: 2. Enviar a Telegram
        run: python generar_whatsapp.py
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
